# Generated by Django 4.2.10 on 2024-02-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, default=254746486487, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
