# Generated by Django 4.2.10 on 2024-02-22 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('1', 'Paracetamol'), ('2', 'Aspirin'), ('3', 'Ibuprofen'), ('4', 'Naproxen'), ('5', 'Diclofenac'), ('6', 'Celecoxib'), ('7', 'Acetaminophen'), ('8', 'Meloxicam'), ('9', 'Piroxicam'), ('10', 'Ketorolac')], max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
