# Generated by Django 4.2.10 on 2024-02-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(choices=[('Paracetamol', 'Paracetamol'), ('Aspirin', 'Aspirin'), ('Ibuprofen', 'Ibuprofen'), ('Naproxen', 'Naproxen'), ('Diclofenac', 'Diclofenac'), ('Celecoxib', 'Celecoxib'), ('Acetaminophen', 'Acetaminophen'), ('Meloxicam', 'Meloxicam'), ('Piroxicam', 'Piroxicam'), ('Ketorolac', 'Ketorolac')], max_length=100),
        ),
    ]
